### ISSUE TITLE
updater seems to fail on trying to create the ".new" configuration file when it already exists

### ISSUE THREAD

**Issue by ulyssessouza** [Axway/elasticsearch-docker-beat#19]
updater seems to fail on trying to create the ".new" configuration file when it already exists (when restarting the container, for example).

The problem with this is that the configuration cannot be updated

**Comment by freignat91** [comment]
I create the branch 'bug_updater' which should fixe the issue.
Could you test please in your env?

**Comment by ulyssessouza** [comment]
Looks fine for me

**Comment by freignat91** [comment]
ok, i gonna merge the branch
